### ISSUE TITLE
这边是飞桨小哥哥，可以详细对下嘛~

### ISSUE THREAD

**Issue by chunzhang-hub** [miraiwk/UGATIT-paddle#3]
hi，同学你好，我是飞桨小哥哥，我们这边想把这个模型转到paddlehub做成一个预训练模型，实现一键的人像动漫化，看看这块可以详细聊聊嘛~wechat：zxy8811666

**Comment by miraiwk** [comment]
已经联系您了， 我把这个issue关闭吧。
