### ISSUE TITLE
How to train rectangular dataset?

### ISSUE THREAD

**Issue by pavelxx1** [miraiwk/UGATIT-paddle#5]
How to train rectangular dataset?

or

How to apply model on rectangular testset
Thanks!

**Comment by miraiwk** [comment]
Hi @pavelxx1 ,

What is the recrangular dataset? Could you please give me a link to the dataset?

You can refer to the format [YOUR_DATASET_NAME](https://github.com/miraiwk/UGATIT-paddle/tree/master/dataset/YOUR_DATASET_NAME)

**Comment by pavelxx1** [comment]
Hi, I mean unaligned image dataset or testset with non quadratic size of image i.e 320x240 or 400x200 etc.

**Comment by miraiwk** [comment]
@pavelxx1 

There are two methods to train rectangular dataset.

Method 1. resize images into quadratic size, then crop them.
Method 2. pad images into quadratic size, then resize and crop them. 

This codebase uses method 1.
https://github.com/miraiwk/UGATIT-paddle/blob/master/UGATIT.py#L98

If necessary, you can modify the code to use method 2 : )

**Comment by pavelxx1** [comment]
Thx,
Question: Can I test model on non quadratic image,
but training has been on quadratic image?

**Comment by miraiwk** [comment]
The image-preprocessing procedure should be consistent between training and testing.

For example, a model is trained by method 1, then method 1 should be used too when testing.

**Comment by pavelxx1** [comment]
I am new in GAN's 
Can you provide code to train my own dataset with images 320x240px
Big thx!
ps: current code has resize my test image from 320x240 to 256x256 output (

**Comment by miraiwk** [comment]
You can modify `train_trasform` and `test_transform` in https://github.com/miraiwk/UGATIT-paddle/blob/master/UGATIT.py#L98.
Sorry that I do not have the code.
